uploads = []
generated = []

[[outputs]]
id = "88PBRgYF8ut5CG7MLKkdS"
uri = "file://exports/phishing_training_dataset.csv"
type = "table"
title = "Training Dataset — 4000 rows, 3 classes (CSV, 828 KB)"

[[outputs]]
id = "hpa8axJjwcA7ydsdJ9_zW"
uri = "file://exports/phishing_training_dataset.json"
type = "unspecified"
title = "Training Dataset — 4000 rows, 3 classes (JSON, 1 MB)"
